version: '3'
services:
        db:
                container_name: ancestra_db
                image: ancestra-db
                ports:
                        - "3306:3306"

        core:
                container_name: ancestra_core
                image: ancestra-core
                depends_on:
                        - "db"
                links:
                        - "db"
                ports:
                        - "5555:5555"
                        - "5556:5556"
                stdin_open: true
                tty: true

        lang:
                container_name: ancestra_lang
                image: ancestra-lang
                ports:
                        - "5557:80"

               
